#!/usr/bin/env sh

path=$(readlink -f "$0")
dir="${path%/*}"

whitelist=$(cat "$dir"/whitelist)
maxDepth=7

"$dir"/generate-list "$whitelist" "$maxDepth"

# genList(){
#    # find -L $whitelist -maxdepth $maxDepth |
#    find -L $(cat $dir/whitelist) -maxdepth $maxDepth |
#       grep -Ev $blacklist \
#          > "$SEARCH_LIST"
# }

# genList


# inotifywait -m -r -e create,delete,move --format "%e" $whitelist |
#    while read -r event; do
#       "$dir"/generate-list "$whitelist" "$maxDepth"
#       # genList
#    done

