#!/usr/bin/env sh

# path=$(readlink -f "$0")
# dir="${path%/*}"

whitelist="\
/home/$USER/Downloads \
$GIT/own \
/disk/Career/FE_Exam/practice \
/disk/Media \
/disk/Phone/Notes \
"

blacklist="node_modules\
|/package.json\
|/\.git\
|/\.gitignore\
|LICENSE\
|README.md\
|\.icons\
|\.themes\
|wallpapers/\
|fonts/\
|Downloads/\
|Media/\
|Linux/\
|dwm/\
|sent/\
"

maxDepth=7

genList(){
   find -L $whitelist -maxdepth $maxDepth |
      grep -Ev $blacklist \
         > "$SEARCH_LIST"
}

genList

inotifywait -m -r -e create,delete,move --format "%e" $whitelist |
   while read -r event; do
      genList
   done

