#!/usr/bin/env sh

[ "$SEARCH_LIST" ] || export SEARCH_LIST=/tmp/search_list

path=$(readlink -f "$0")
dir="${path%/*}"

# blacklist="node_modules\
# |/package.json\
# |/\.git\
# |/\.gitignore\
# |LICENSE\
# |README.md\
# |\.icons\
# |\.themes\
# |wallpapers/\
# |fonts/\
# |Downloads/\
# |Media/\
# |Linux/\
# |dwm/\
# |sent/\
# "

blacklist=$(grep -Ev "^#|^$" "$dir"/blacklist | sed 's/^\./\\./' | tr '\n' '|' | sed 's/|$//')

echo $blacklist

find -L $(grep -v "^#" "$dir"/whitelist) -maxdepth 7 |
   grep -Ev "$blacklist" \
      > "$SEARCH_LIST"
