#!/usr/bin/env sh

[ "$SEARCH_LIST" ] || export SEARCH_LIST=/tmp/search_list
path=$(readlink -f "$0")
dir="${path%/*}"

whitelist=$(grep -v "^#" "$dir"/whitelist)
blacklist=$(grep -Ev "^#|^$" "$dir"/blacklist | sed 's/^\./\\./' | tr '\n' '|' | sed 's/|$//')
maxDepth=7

find -L $whitelist -maxdepth $maxDepth |
   grep -Ev "$blacklist" \
      > "$SEARCH_LIST"
