#!/bin/sh

PATH_LIST=/tmp/searchlist
CONFIG=~/.config/boltrc

tmux_search() {
   /usr/local/bin/launch -t 2> /dev/null
   if pidof tmux; then
      tmux new-window
   else
      tmux new-session -s "home" -d \; switch-client
   fi
   if pidof "$TERMINAL"; then
      [ "$(pidof "$TERMINAL")" != "$(xdo pid)" ] &&
         xdo activate -N "st-256color"
   else
      "$TERMINAL" -e tmux attach &
   fi
   tmux send "$0 --fzf-search" "Enter"
}

_get_config() {
   CURRENT_IFS=$IFS
   IFS=$(printf ';')
   for line in $1; do
      printf "%s" "$line"
   done
   IFS=$CURRENT_IFS
}

_get_match() {
   while IFS= read -r line; do
      case $line in
         *"/$1") echo "$line" ;;
      esac
   done < "$PATH_LIST"
}

fzf_search() {
   QUERY=$(awk -F / '{print $NF}' "$1" | fzf) || exit 0
   RESULT=$(_get_match "$QUERY")
   /usr/local/bin/faint "$RESULT"
}

generate() {
   . $1
   FILTERS=$(_get_config "$FILTERS" | awk '{printf "%s\\|",$0;}' | sed -e 's/|\./|\\./g' -e 's/\\|$//g')
   find $(_get_config "$PATHS") -maxdepth "$MAX_DEPTH" -type d \
      ! -regex ".*\($FILTERS\).*" | sort > "$2"
}

main() {
   case $1 in
      --generate | -g) generate $CONFIG $PATH_LIST ;;
      --fzf-search | -f) fzf_search $PATH_LIST ;;
      --tmux-search | -t) tmux_search ;;
   esac
}
main "$1"
